CREATE TABLE staff (
    staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    contract_type VARCHAR(20) NOT NULL CHECK (contract_type IN ('Casual','Full Time','Part Time')),
    standard_hours DECIMAL(5,2) NOT NULL DEFAULT 38,
    role VARCHAR(50),                      -- job title only; access comes from user_roles
    standard_rate DECIMAL(8,2) NOT NULL,
    overtime_rate DECIMAL(8,2) NOT NULL,
    credential_ref VARCHAR(100),
    hours_type VARCHAR(10) NOT NULL DEFAULT 'Weekly' CHECK (hours_type IN ('Weekly','Patterned')),
    pattern_days VARCHAR(30),
    pattern_start TIME,
    pattern_end TIME,
    pin_hash VARCHAR(100),                 -- bcrypt hash created by the app
    pin_expires_at TIMESTAMPTZ,
    annual_leave_hours DECIMAL(6,2) NOT NULL DEFAULT 0,
    personal_leave_hours DECIMAL(6,2) NOT NULL DEFAULT 0,
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(30),
    removed_at TIMESTAMPTZ,                -- soft delete keeps time, payroll and audit history
    removed_by INTEGER REFERENCES staff(staff_id),
    created_at TIMESTAMPTZ DEFAULT now(),
    CHECK (hours_type = 'Weekly' OR (pattern_days IS NOT NULL AND pattern_start IS NOT NULL AND pattern_end IS NOT NULL)),
    CHECK (pin_hash IS NULL OR pin_expires_at IS NOT NULL)
);

CREATE TABLE stations (
    station_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    location VARCHAR(100),
    id_type VARCHAR(20) CHECK (id_type IN ('QR','PIN','Face','Fingerprint')),
    online BOOLEAN NOT NULL DEFAULT FALSE,
    last_seen TIMESTAMPTZ
);

CREATE TABLE roster (
    roster_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL REFERENCES staff(staff_id),
    shift_date DATE NOT NULL,
    start_time TIME NOT NULL,
    expected_hours DECIMAL(4,2) NOT NULL,
    team VARCHAR(50),
    site VARCHAR(50),
    station_id INTEGER REFERENCES stations(station_id)
);

-- ---------- Rules, clocking and breaks ----------

CREATE TABLE compliance_rules (
    rule_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(50) NOT NULL,
    max_hours_without_break DECIMAL(4,2),
    daily_overtime_threshold DECIMAL(4,2),
    weekly_overtime_threshold DECIMAL(4,2)
);

CREATE TABLE time_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL REFERENCES staff(staff_id),
    station_id INTEGER REFERENCES stations(station_id),
    event_type VARCHAR(20) NOT NULL CHECK (event_type IN ('clock_in','clock_out','break_start','break_end')),
    event_timestamp TIMESTAMPTZ NOT NULL,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    synced_at TIMESTAMPTZ,
    is_override BOOLEAN NOT NULL DEFAULT FALSE,
    override_reason VARCHAR(200),
    override_method VARCHAR(20) CHECK (override_method IN ('Admin Portal','Supervisor PIN')),
    is_unrostered BOOLEAN NOT NULL DEFAULT FALSE,
    sync_status VARCHAR(20) NOT NULL DEFAULT 'Synced' CHECK (sync_status IN ('Pending','Synced','Failed')),
    created_by INTEGER REFERENCES staff(staff_id),
    rule_id INTEGER REFERENCES compliance_rules(rule_id)
);

CREATE TABLE break_reasons (
    reason_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(30) NOT NULL,
    is_paid BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE breaks (
    break_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_event_id INTEGER NOT NULL REFERENCES time_events(event_id),
    end_event_id INTEGER REFERENCES time_events(event_id),
    reason_id INTEGER REFERENCES break_reasons(reason_id),
    note VARCHAR(200),
    CHECK (end_event_id IS NULL OR end_event_id <> start_event_id)
);

CREATE TABLE public_holidays (
    holiday_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE NOT NULL,
    name VARCHAR(100) NOT NULL,
    state VARCHAR(3) NOT NULL DEFAULT 'SA' CHECK (state IN ('NAT','SA','NSW','VIC','QLD','WA','TAS','NT','ACT')),
    UNIQUE (holiday_date, state)
);

-- ---------- Payroll ----------

CREATE TABLE payroll_runs (
    run_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    step INTEGER NOT NULL DEFAULT 1 CHECK (step BETWEEN 1 AND 4),   -- 1 review, 2 approve, 3 payslips, 4 export
    approved_by INTEGER REFERENCES staff(staff_id),
    approved_at TIMESTAMPTZ,
    updated_by INTEGER REFERENCES staff(staff_id),
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (period_start, period_end),
    CHECK (period_end >= period_start)
);

CREATE TABLE payroll_summary (
    payroll_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id INTEGER REFERENCES payroll_runs(run_id),
    staff_id INTEGER NOT NULL REFERENCES staff(staff_id),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    ordinary_hours DECIMAL(6,2),
    overtime_hours DECIMAL(6,2),
    weekend_hours DECIMAL(6,2) NOT NULL DEFAULT 0,
    public_holiday_hours DECIMAL(6,2) NOT NULL DEFAULT 0,
    penalty_flag BOOLEAN GENERATED ALWAYS AS (weekend_hours > 0 OR public_holiday_hours > 0) STORED,
    total_pay DECIMAL(10,2),
    UNIQUE (staff_id, period_start),
    CHECK (period_end >= period_start)
);

-- ---------- Exceptions, corrections and audit ----------

CREATE TABLE exceptions (
    exception_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL REFERENCES staff(staff_id),
    event_id INTEGER REFERENCES time_events(event_id),
    rule_id INTEGER REFERENCES compliance_rules(rule_id),
    exception_type VARCHAR(40) NOT NULL CHECK (exception_type IN (
        'Missing clock-out',
        'Break overdue',
        'Unrostered attempt',
        'Clocked in at wrong station'
    )),
    exception_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Open' CHECK (status IN ('Open','Reviewed','Resolved')),
    manager_notified BOOLEAN NOT NULL DEFAULT FALSE,
    detected_at TIMESTAMPTZ DEFAULT now(),
    notes VARCHAR(200)
);

CREATE TABLE time_adjustments (
    adjustment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL REFERENCES staff(staff_id),
    event_id INTEGER REFERENCES time_events(event_id),
    action VARCHAR(10) NOT NULL CHECK (action IN ('ADD','EDIT','DELETE')),
    old_timestamp TIMESTAMPTZ,
    new_timestamp TIMESTAMPTZ,
    reason VARCHAR(200) NOT NULL,
    override_method VARCHAR(20) CHECK (override_method IN ('Admin Portal','Supervisor PIN')),
    requested_by INTEGER NOT NULL REFERENCES staff(staff_id),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    approver INTEGER REFERENCES staff(staff_id),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected')),
    decided_at TIMESTAMPTZ,
    CHECK (status = 'Pending' OR (approver IS NOT NULL AND decided_at IS NOT NULL)),
    CHECK (approver IS NULL OR approver <> requested_by)
);

CREATE TABLE audit_logs (
    audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(50) NOT NULL,
    record_id INTEGER NOT NULL,
    action VARCHAR(20) NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
    reason VARCHAR(200) NOT NULL,
    changed_by INTEGER NOT NULL REFERENCES staff(staff_id),
    changed_at TIMESTAMPTZ DEFAULT now(),
    adjustment_id INTEGER REFERENCES time_adjustments(adjustment_id)
);

-- ---------- Leave ----------

CREATE TABLE leave_requests (
    leave_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER NOT NULL REFERENCES staff(staff_id),
    type VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    days DECIMAL(4,1),
    note VARCHAR(200),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected')),
    decided_by INTEGER REFERENCES staff(staff_id),
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    CHECK (end_date >= start_date)
);

-- ---------- Sign-in and security (kept from the app) ----------

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id INTEGER UNIQUE REFERENCES staff(staff_id),   -- optional: the farm owner can be admin without a staff record
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100),
    totp_secret VARCHAR(255),
    totp_pending VARCHAR(255),
    station_pin_hash VARCHAR(255),
    disabled BOOLEAN NOT NULL DEFAULT FALSE,
    password_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE user_roles (
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    role VARCHAR(30) NOT NULL CHECK (role IN ('Office Admin','Roster Admin','Manager/Supervisor','Worker')),
    PRIMARY KEY (user_id, role)
);

CREATE TABLE sessions (
    token_hash VARCHAR(128) PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    portal VARCHAR(20),
    mfa_verified BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_failures INTEGER NOT NULL DEFAULT 0,
    workspace VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT now(),
    last_seen TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    ip VARCHAR(64),
    user_agent VARCHAR(255)
);

CREATE TABLE login_attempts (
    email VARCHAR(255) NOT NULL,
    portal VARCHAR(20) NOT NULL,
    failures INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    PRIMARY KEY (email, portal)
);

-- ---------- Indexes for the common queries ----------

CREATE INDEX idx_roster_staff_date ON roster (staff_id, shift_date);
CREATE INDEX idx_roster_date ON roster (shift_date);
CREATE INDEX idx_time_events_staff_time ON time_events (staff_id, event_timestamp);
CREATE INDEX idx_time_events_time ON time_events (event_timestamp);
CREATE INDEX idx_breaks_start_event ON breaks (start_event_id);
CREATE INDEX idx_exceptions_open ON exceptions (exception_date) WHERE status = 'Open';
CREATE INDEX idx_adjustments_pending ON time_adjustments (requested_at) WHERE status = 'Pending';
CREATE INDEX idx_leave_staff ON leave_requests (staff_id, start_date);
CREATE INDEX idx_sessions_user ON sessions (user_id);
